<img src="logo_ifba.jpg" alt="jpg_python" width="100" height="200">
<br><br>
<div align="center"><span style="font-size: 26px;"><strong>Atividade Aplicada à Computação</strong></span></div>
<br></br>
<div align="center"><span style="font-size: 26px;"><strong>Matrizes</strong></span></div>
<br></br>
<img src="python_gif.gif" alt="gif_python" width="80">

# <font color='red'>1. Operações Com Matrizes</font>

Nesta atividade usaremos o Jupyter Notebook (ou o Google Colab) para efetuar cálculos envolvendo matrizes aplicados a um exemplo de cálculo de preços de produtos.

Em matemática costumamos descrever uma matriz de $n$ linhas e $m$ colunas da seguinte forma:

$$A_{n \times m} = \begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1m}\\
a_{21} & a_{22} & \ldots & a_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} & a_{n2} & \ldots & a_{nm}\\
\end{bmatrix}$$

Note que a indexação de um elemento começa de $(1,1)$, isto é, $a_{11}$ é o elemento que está na localizado na linha $1$ e coluna $1$. Um elemento $a_{ij}$ está localizado na linha $i$ e coluna $j$.

Em Python descrevemos uma matriz com indexação começando de $0$:

$$A_{n \times m} = \begin{bmatrix}
a_{00} & a_{01} & \ldots & a_{0(m-1)}\\
a_{10} & a_{11} & \ldots & a_{0(m-1)}\\
\vdots & \vdots & \vdots & \vdots\\
a_{(n-1)0} & a_{(n-1)1} & \ldots & a_{(n-1)(m-1)}\\
\end{bmatrix}$$

Note que a indexação de um elemento começa de $(0,0)$, isto é, $a_{00}$ é o elemento que está na localizado na linha $1$ e coluna $1$. Um elemento $a_{ij}$ está localizado na linha $i-1$ e coluna $j-1$.

## <font color='blue'>1.1 Inserindo Uma Matriz</font>

Vejamos como inserir a matriz:
$$A = \begin{bmatrix}
1 & 2 & 3\\
2 & 1 & 0\\
3 & 4 & 1\\
\end{bmatrix}$$


In [ ]:
# Inserindo a matriz A
import numpy as np #Módulo necessário

A = np.matrix([[1,2,3],[2,1,0],[3,4,1]])

In [ ]:
# Vizualizando a matriz
print(A)

## <font color='blue'>1.2 Consultando Dimensão e Elementos Internos de Uma Matriz</font>

Veremos a seguir como consultar a dimensão (tamanho) de uma matriz bem como acessar elementos internos, linhas e colunas.

### <font color='blue'>1.2.1 Consultando a Dimensão</font>

Considere a matriz $B$:
$$B = \begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix}$$

In [ ]:
# Inserindo a matriz B
import numpy as np 

B = np.matrix([[1,2,-1],[-3,1,1]])

In [ ]:
# Consultando a dimensão de uma matriz
dim = B.shape
print(dim)

### <font color='blue'>1.2.2 Consultando Elementos, Linhas e Colunas</font>

Em Python a indexação de matrizes começa de zero, isto é, para consultar um elemento localizado na coluna $j$ da linha $i$ devemos consultar usando $i-1$ e $j-1$.

Considere a matriz $B$:
$$C = \begin{bmatrix}
-1 & 1 & 4\\
5 & 3 & 2\\
7 & 9 & 6\\
1 & -6 & 8\\
\end{bmatrix}$$

In [ ]:
# Inserindo a matriz C
import numpy as np 

C = np.matrix([[-1,1,4],[5,3,2],[7,9,6],[1,-6,8]])

In [ ]:
# Consultando C(i,j)
elemento = C[0,0]
print(elemento)

A consulta de linhas e colunas é, também, bastante simples.

In [ ]:
## Consultando a linha i (indexação começa de 0)
linha = C[0,:]     #mude para 1
print(linha)

In [ ]:
# Consultando a linha j (indexação começa de 0)
coluna = C[:,0]
print(coluna)

## <font color='blue'>1.3 Operações Com Matrizes</font>

A seguir apresentaremos algumas operações básicas usando matrizes. Elas serão extremamente úteis com bastante aplicações nas mais diversas áreas.


### <font color='blue'>1.3.1 Multiplicação de Uma Matriz Por Um Escalar Real ($\alpha \in \mathbb{R}$)</font>

Seja $A$ uma matriz $n \times m$ e $\alpha$ um escalar. Define-se o produto de $\alpha$ por $A$ como sendo o produto de cada elemento de $A$ por $\alpha$. Em símbolos, temos:

$$\alpha A_{n \times m} = \alpha\begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1m}\\
a_{21} & a_{22} & \ldots & a_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} & a_{n2} & \ldots & a_{nm}\\
\end{bmatrix} = \begin{bmatrix}
\alpha a_{11} & \alpha a_{12} & \ldots & \alpha a_{1m}\\
\alpha a_{21} & \alpha a_{22} & \ldots & \alpha a_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
\alpha a_{n1} & \alpha a_{n2} & \ldots & \alpha a_{nm}\\
\end{bmatrix}
$$

<font color='blue'> **Exemplo:** Calcule o $2A$ em que
<br><br>
$$A = \begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix}$$
<br><br>
**Solução:** Temos que
<br><br>
$$
2A= 
2\begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} 
=
\begin{bmatrix}
2\cdot1 & 2\cdot2 & 2\cdot(-1)\\
2\cdot(-3) & 2\cdot1 & 2\cdot1\\
\end{bmatrix} 
= \begin{bmatrix}
2 & 4 & -2\\
-6 & 2 & 2\\
\end{bmatrix} 
$$



Vejamos o mesmo exemplo usando programação.

In [13]:
# Inserindo A
import numpy as np

A = np.matrix([[1,2,-1],[-3,1,1]], dtype = 'float')

In [14]:
# Multiplincando a por 2
A2 = 2*A
print(A2)

[[ 2.  4. -2.]
 [-6.  2.  2.]]


### <font color='blue'>1.3.2 Soma e Subtração de Matrizes Matrizes</font>

Sejam $A$ e $B$ matrizes de mesmo número de linhas e colunas, isto é, $A = A_{n \times m}$ e $B = B_{n \times m}$. Define-se a <u>soma</u> de $A$ com $B$ como sendo a matriz $C$ que soma os elementos das posições correspondentes. Em símbolos, temos:

$$A_{n \times m} + B_{n \times m} = \begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1m}\\
a_{21} & a_{22} & \ldots & a_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} & a_{n2} & \ldots & a_{nm}\\
\end{bmatrix} 
+
\begin{bmatrix}
b_{11} & b_{12} & \ldots & b_{1m}\\
b_{21} & b_{22} & \ldots & b_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
b_{n1} & b_{n2} & \ldots & b_{nm}\\
\end{bmatrix} = $$

$$\,\,\,\,\,\,\,=
\begin{bmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \ldots & a_{1m} + b_{1m}\\
a_{21} + b_{21} & a_{22} + b_{22} & \ldots & a_{2m} + b_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} + b_{n1} & a_{n2} + b_{n2} & \ldots & a_{nm} + b_{nm}\\
\end{bmatrix}
$$

<font color='blue'> **Exemplo:** Some as matrizes
<br><br>
$$A = \begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} \,\,\,\, e \,\,\,\, B = \begin{bmatrix}
2 & 1 & -1\\
0 & 4 & 2\\
\end{bmatrix} $$
<br><br>
**Solução:** Temos que
<br><br>
$$
A + B = 
\begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} 
+ 
\begin{bmatrix}
2 & 1 & -1\\
0 & 4 & 2\\
\end{bmatrix} 
=$$
<br><br>
$$=    
\begin{bmatrix}
1+2 & 2+1 & -1+(-1)\\
-3+0 & 1+4 & 1+2\\
\end{bmatrix}
=
\begin{bmatrix}
3 & 3 & -2\\
-3 & 5 & 3\\
\end{bmatrix}
$$



Vejamos o mesmo exemplo usando programação.

In [10]:
# Inserindo A e B
import numpy as np

A = np.matrix([[1,2,-1],[-3,1,1]], dtype = 'float')
B = np.matrix([[2,1,-1],[0,4,2]], dtype = 'float')

In [5]:
# Soma de A com B
soma = A + B
print(soma)

[[ 3.  3. -2.]
 [-3.  5.  3.]]


Sejam $A$ e $B$ matrizes de mesmo número de linhas e colunas, isto é, $A = A_{n \times m}$ e $B = B_{n \times m}$. Define-se a <u>subtração</u> de $A$ com $B$ como sendo a matriz $C$ que subtrai os elementos das posições correspondentes. Em símbolos, temos:

$$A_{n \times m} - B_{n \times m} = \begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1m}\\
a_{21} & a_{22} & \ldots & a_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} & a_{n2} & \ldots & a_{nm}\\
\end{bmatrix} 
-
\begin{bmatrix}
b_{11} & b_{12} & \ldots & b_{1m}\\
b_{21} & b_{22} & \ldots & b_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
b_{n1} & b_{n2} & \ldots & b_{nm}\\
\end{bmatrix} = $$

$$\,\,\,\,\,\,\,=
\begin{bmatrix}
a_{11} - b_{11} & a_{12} - b_{12} & \ldots & a_{1m} - b_{1m}\\
a_{21} - b_{21} & a_{22} - b_{22} & \ldots & a_{2m} - b_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} - b_{n1} & a_{n2} - b_{n2} & \ldots & a_{nm} - b_{nm}\\
\end{bmatrix}
$$

<font color='blue'>**Exemplo:** Calcule a subtração $A-B$ das matrizes 
<br><br>
$$A = \begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} \,\,\,\, e \,\,\,\, B = \begin{bmatrix}
2 & 1 & -1\\
0 & 4 & 2\\
\end{bmatrix} $$
<br><br>
**Solução:** Temos que
<br><br>
$$A - B = 
\begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} 
- 
\begin{bmatrix}
2 & 1 & -1\\
0 & 4 & 2\\
\end{bmatrix} 
=$$
<br><br>
$$=    
\begin{bmatrix}
1-2 & 2-1 & -1-(-1)\\
-3-0 & 1-4 & 1-2\\
\end{bmatrix}
=
\begin{bmatrix}
-1 & 1 & 0\\
-3 & -3 & -1\\
\end{bmatrix}
$$



Vejamos o mesmo exemplo usando programação.

In [7]:
# Inserindo A e B
import numpy as np

A = np.matrix([[1,2,-1],[-3,1,1]], dtype = 'float')
B = np.matrix([[2,1,-1],[0,4,2]], dtype = 'float')

In [9]:
# Subtração de A por B
sub = A - B
print(sub)

[[-1.  1.  0.]
 [-3. -3. -1.]]


### <font color='blue'>1.3.3 Multiplicação de Matrizes</font>

Sejam $A$ uma matriz de dimensão $n \times m$ e $B$ uma matriz de dimensão $m \times p$. O produto de $A$ por $B$, denotado por $AB$, é uma matriz $C$ de dimensão $n \times p$, em que cada elemento $c_{ij}$ é calculado pela multiplicação das linhas de $A$ pelos elementos correspondentes das colunas de $B$, seguido da soma desses produtos. Em símbolos, temos:

$$\begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1m}\\
a_{21} & a_{22} & \ldots & a_{2m}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} & a_{n2} & \ldots & a_{nm}\\
\end{bmatrix}
\cdot
\begin{bmatrix}
b_{11} & b_{12} & \ldots & b_{1p}\\
b_{21} & b_{22} & \ldots & b_{2p}\\
\vdots & \vdots & \vdots & \vdots\\
b_{m1} & b_{m2} & \ldots & b_{mp}\\
\end{bmatrix} = $$
$$\,\,\,\,\,\,\,=
\begin{bmatrix}
a_{11} \cdot b_{11} + a_{12} \cdot b_{21} + \ldots + a_{1m} \cdot b_{m1} & a_{11} \cdot b_{12} + a_{12} \cdot b_{22} + \ldots + a_{1m} \cdot b_{m2} & \ldots & a_{11} \cdot b_{1p} + a_{12} \cdot b_{2p} + \ldots + a_{1m} \cdot b_{mp}\\
a_{21} \cdot b_{11} + a_{22} \cdot b_{21} + \ldots + a_{2m} \cdot b_{m1} & a_{21} \cdot b_{12} + a_{22} \cdot b_{22} + \ldots + a_{2m} \cdot b_{m2} & \ldots & a_{21} \cdot b_{1p} + a_{22} \cdot b_{2p} + \ldots + a_{2m} \cdot b_{mp}\\
\vdots & \vdots & \vdots & \vdots\\
a_{n1} \cdot b_{11} + a_{n2} \cdot b_{21} + \ldots + a_{nm} \cdot b_{m1} & a_{n1} \cdot b_{12} + a_{n2} \cdot b_{22} + \ldots + a_{nm} \cdot b_{m2} & \ldots & a_{n1} \cdot b_{1p} + a_{n2} \cdot b_{2p} + \ldots + a_{nm} \cdot b_{mp}\\
\end{bmatrix}$$

<font color='blue'>**Exemplo:** Calcule o produto $AB$ das matrizes 
<br><br>
$$A = \begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} \,\,\,\, e \,\,\,\, 
B = \begin{bmatrix}
2 & -2 & -1\\
0 & 3 & 2\\
2 & 1 & 1\\
\end{bmatrix} $$
<br><br>
**Solução:** Temos que
<br><br>
$$A - B = 
\begin{bmatrix}
1 & 2 & -1\\
-3 & 1 & 1\\
\end{bmatrix} 
\cdot 
\begin{bmatrix}
2 & -2 & -1\\
0 & 3 & 2\\
2 & 1 & 1\\
\end{bmatrix} 
=$$
<br><br>
$$=    
\begin{bmatrix}
1\cdot2 + 2\cdot0 + -1\cdot2 & 1\cdot(-2) + 2\cdot3 + -1\cdot1 & 1\cdot(-1) + 2\cdot2 + -1\cdot1\\
-3\cdot2 + 1\cdot0 + 1\cdot2 & -3\cdot(-2) + 1\cdot3 + 1\cdot1 & -3\cdot(-1) + 1\cdot2 + 1\cdot1\\
\end{bmatrix}
=$$
<br><br>   
$$=\begin{bmatrix}
2 + 0 - 2 & -2 + 6 -1 & -1 + 4 -1\\
-6 + 0 + 2 & 6 + 3 + 1 & 3 + 2 + 1\\
\end{bmatrix}=
\begin{bmatrix}
0 & 3 & 2\\
4 & 10 & 6\\
\end{bmatrix}
$$



Vejamos o mesmo exemplo usando programação.

In [17]:
# Inserindo A e B
import numpy as np

A = np.matrix([[1,2,-1],[-3,1,1]], dtype = 'float')
B = np.matrix([[2,-2,-1],[0,3,2],[2,1,1]], dtype = 'float')

In [18]:
# Multiplicação de A por B
mult = np.dot(A,B)
print(mult)

[[ 0.  3.  2.]
 [-4. 10.  6.]]


**Exemplo:** Uma doceira preparou $3$ tipos de salgados usando as quantidades de ingredientes conforme a tabela abaixo:
<br><br>
|          |  Ovo  | Farinha | Açúcar | Carne |
|:--------:|:-----:|:-------:|:------:|:-----:|
| Pastéis  |   3   |    6    |   1    |   3   |
| Empadas  |   4   |    4    |   2    |   2   |
| Quibes   |   1   |    1    |   1    |   6   |
<br><br>

Os custos das poções unitárias dos produtos usados é dado na tabela a seguir:
<br><br>

|Ingredientes|  Ovo  |
|:----------:|:-----:|
| Ovo        | 0,20  |
| Farinha    | 0,30  |
| Açúcar     | 0,50  |
| Carne      | 0,80  |

<br><br>

a) Calcule o preço de cada salgado.

b) Calcule o preço de cada salgado em que a quantidade de carne utilizada será reduzida em $25\%$.

c) Calcule o preço de cada salgado se o preço dos ingredientes aumentou $10\%$ seguidamente à redução de $25\%$ na quantidade de carne usada.

Solução: a) Note que trata-se de um produto das matrizes associadas às quantidades de ingredientes e do preço. Isto é,
<br><br>
$$quantidade*preço = \begin{bmatrix}
3 & 6 & 1 & 3\\
4 & 4 & 2 & 2\\
1 & 1 & 1 & 6\\
\end{bmatrix} \cdot
\begin{bmatrix}
0,2 \\
0,3 \\
0,5 \\
0,8 \\
\end{bmatrix} $$
<br>
Uma vez que já sabemos programar o produto usemos esta maravilhosa fucionalidade.

In [24]:
# Inserindo A e B
import numpy as np

quantidades = np.matrix([[3,6,1,3],[4,4,2,2],[1,1,1,6]], dtype = 'float')
precos = np.matrix([[0.2],[0.3],[0.5],[0.8]], dtype = 'float')

In [33]:
valores = np.dot(quantidades,preco)
print(f'Pastel: R$ {round(valores[0,0],2)}')
print(f'Empada: R$ {round(valores[1,0],2)}')
print(f'Quibe: R$ {round(valores[2,0],2)}')

Pastel: R$ 5.3
Empada: R$ 4.6
Quibe: R$ 5.8


Solução: b) Note que trata-se de um produto das matrizes associadas às quantidades de ingredientes com a redução de $25\%$ e do preço. Isto é,
<br><br>
$$quantidade*preço = \begin{bmatrix}
3 & 6 & 1 & (3-25\%)\\
4 & 4 & 2 & (2-25\%)\\
1 & 1 & 1 & (6-25\%)\\
\end{bmatrix} \cdot
\begin{bmatrix}
0,2 \\
0,3 \\
0,5 \\
0,8 \\
\end{bmatrix} $$
<br>
Uma vez que já sabemos programar o produto usemos esta maravilhosa fucionalidade.

In [37]:
# Ajustando a matriz quantidade
import numpy as np

quantidades = np.matrix([[3, 6, 1, 3], [4, 4, 2, 2], [1, 1, 1, 6]], dtype='float')

# Obtém a quarta coluna
col4 = quantidades[:, 3]

# Reduz as quantidades em 25%
col4_ajust = col4 * 0.75

# Atualiza a quarta coluna na matriz original
quantidades[:, 3] = col4_ajust

print("Quantidades reduzidas em 25% na quarta coluna:")
print(quantidades)


Quantidades reduzidas em 25% na quarta coluna:
[[3.   6.   1.   2.25]
 [4.   4.   2.   1.5 ]
 [1.   1.   1.   4.5 ]]


In [38]:
# Calculando os novos valores
valores = np.dot(quantidades,preco)
print(f'Pastel: R$ {round(valores[0,0],2)}')
print(f'Empada: R$ {round(valores[1,0],2)}')
print(f'Quibe: R$ {round(valores[2,0],2)}')

Pastel: R$ 4.7
Empada: R$ 4.2
Quibe: R$ 4.6


Solução: c) Note que trata-se de um produto das matrizes associadas às quantidades de ingredientes com a redução de $25\%$ e do preço aumentado de $10\%$. Isto é,
<br><br>
$$quantidade*preço = \begin{bmatrix}
3 & 6 & 1 & (3-25\%) \\
4 & 4 & 2 & (2-25\%) \\
1 & 1 & 1 & (6-25\%) \\
\end{bmatrix} \cdot
\begin{bmatrix}
0,2 + 10\% \\
0,3 + 10\% \\
0,5 + 10\% \\
0,8 + 10\% \\
\end{bmatrix} $$
<br>
Uma vez que já sabemos programar o produto usemos esta maravilhosa fucionalidade.

In [43]:
# Ajustando a matriz quantidade
import numpy as np

precos = np.matrix([[0.2],[0.3],[0.5],[0.8]], dtype = 'float')

# Obtém a quarta coluna
col1 = preco[:, 0]

# Aumento dos valores em 10%
col1_ajust = col1 * 1.10

# Atualiza a coluna na matriz original
preco[:, 0] = col1_ajust

print("Preços aumentados em 10%:")
print(preco)


Preços aumentados em 10%:
[[0.22]
 [0.33]
 [0.55]
 [0.88]]


In [44]:
# Calculando os novos valores
valores = np.dot(quantidades,preco)
print(f'Pastel: R$ {round(valores[0,0],2)}')
print(f'Empada: R$ {round(valores[1,0],2)}')
print(f'Quibe: R$ {round(valores[2,0],2)}')

Pastel: R$ 5.17
Empada: R$ 4.62
Quibe: R$ 5.06
